### ISSUE TITLE
Request for node16 update due to interruption of node12 support of Github Action

### ISSUE THREAD

**Issue by jjunohj** [rahul-jha98/github-stats-transparent#14]
After creating new ACCESS_TOKEN with permission `repo` and `read:user`on, I pressed Run Workflow button.
But the error occured and it says below.

```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2, actions/cache@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

I think this is because Github Actions stopped to provide node12 after Summer 2023. 

I think you need to update your actions to run on Node 16 instead of Node 12.
([Actions configuration settings](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions))

[here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) is the reference site from Github Blog

**Comment by nerdrun** [comment]
As @jjunohj mentioned earlier, I've encountered exactly the same error while running the workflow.
I tried to fix that. However it has been occurred due to your Actions envionment.
