### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by fayasnoushad** [rahul-jha98/github-stats-transparent#3]
Please remove border of stats

**Comment by rahul-jha98** [comment]
I will try adding the option to disable borders using another environment secret. Meanwhile if you need to remove border from your generated stats you can make the following changes in your cloned repo. 

In line 13 of the files `templates/languages.svg` and `templates/overview.svg` change stroke value to `#00000000;`

With that done the github action will generate images which will have no borders.

**Comment by fayasnoushad** [comment]
Thanks
